### ISSUE TITLE
organization identifiers fail due to wrong mapping

### ISSUE THREAD

**Issue by breyten** [openstate/open-raadsinformatie#52]
```
2017-12-06 12:25:59] [celery.app.trace] [ERROR] - Task ocd_backend.loaders.ElasticsearchLoader[c257f458-ede1-43ff-a74f-783aae113f89] raised unexpected: RequestError(400, u'illegal_argument_exception', {u'status': 400, u'error': {u'root_cause': [{u'reason': u'mapper [organization.identifiers.identifier] of different type, current_type [long], merged_type [text]', u'type': u'illegal_argument_exception'}], u'type': u'illegal_argument_exception', u'reason': u'mapper [organization.identifiers.identifier] of different type, current_type [long], merged_type [text]'}})
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/celery/app/trace.py", line 374, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/celery/app/trace.py", line 629, in __protected_call__
    return self.run(*args, **kwargs)
  File "/opt/ori/ocd_backend/loaders/__init__.py", line 74, in run
    return super(ElasticsearchLoader, self).run(*args, **kwargs)
  File "/opt/ori/ocd_backend/loaders/__init__.py", line 42, in run
    self.load_item(*item)
  File "/opt/ori/ocd_backend/loaders/__init__.py", line 85, in load_item
    body=doc, id=object_id)
  File "/usr/local/lib/python2.7/site-packages/elasticsearch/client/utils.py", line 73, in _wrapped
    return func(*args, params=params, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/elasticsearch/client/__init__.py", line 300, in index
    _make_path(index, doc_type, id), params=params, body=body)
  File "/usr/local/lib/python2.7/site-packages/elasticsearch/transport.py", line 312, in perform_request
    status, headers, data = connection.perform_request(method, url, params, body, ignore=ignore, timeout=timeout)
  File "/usr/local/lib/python2.7/site-packages/elasticsearch/connection/http_urllib3.py", line 128, in perform_request
    self._raise_error(response.status, raw_data)
  File "/usr/local/lib/python2.7/site-packages/elasticsearch/connection/base.py", line 125, in _raise_error
    raise HTTP_EXCEPTIONS.get(status_code, TransportError)(status_code, error_message, additional_info)
```

This happens with goirle (GO). Not sure why though

**Comment by jurrian** [comment]
It seems there might be a mapping conflict, perhaps with the old data? I can't really see why since nothing has changed recently for goapi. I think I resolved it by purging elastic and uploading the template again, but that might be problematic for production ;)
See https://github.com/elastic/elasticsearch/issues/17092 for more info.

**Comment by breyten** [comment]
This was a fairly empty local install ;). I'll completely empty it now and test again (but these issues arrise from non-strict mapping anyway)

**Comment by breyten** [comment]
Also happpens with completely empty install.

**Comment by jurrian** [comment]
GO committees happen to have integer identifiers, while the ES mapping is string. This causes the exception. Simply casting to unicode as committed should solve the problem.

**Comment by breyten** [comment]
This is not going away by itself ;)

**Comment by breyten** [comment]
Uhm, nvm, I missed the commit

**Comment by breyten** [comment]
This keeps happening, also with an empty database

**Comment by breyten** [comment]
FYI: data migration fails on this too
