### ISSUE TITLE
Meetingitems sometimes (?) do not have a doc_type

### ISSUE THREAD

**Issue by breyten** [openstate/open-raadsinformatie#53]
```
[2017-12-06 12:26:10] [celery.app.trace] [ERROR] - Task ocd_backend.transformers.BaseTransformer[c2cf2856-ab7d-49ab-a74d-ebec0b66f899] raised unexpected: AttributeError("'MeetingItem' object has no attribute 'doc_type'",)
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/celery/app/trace.py", line 374, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/celery/app/trace.py", line 629, in __protected_call__
    return self.run(*args, **kwargs)
  File "/opt/ori/ocd_backend/transformers/__init__.py", line 37, in run
    return self.transform_item(*args, item=item)
  File "/opt/ori/ocd_backend/transformers/__init__.py", line 87, in transform_item
    item.doc_type,
AttributeError: 'MeetingItem' object has no attribute 'doc_type'
```

This happens at least with a GO municipality (I'm not sure why though)

**Comment by jurrian** [comment]
The goapi MeetingItem had a custom constructor which wasn't updated yet.. I committed a fix thas should make it work. Let me know!

**Comment by breyten** [comment]
Nope, sorry ;)

Now there's this:
```
[2017-12-06 16:17:38] [celery.app.trace] [ERROR] - Task ocd_backend.transformers.BaseTransformer[1cc3a901-71ca-4f3d-838b-6ae03ee3ced3] raised unexpected: KeyError('id',)
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/celery/app/trace.py", line 374, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/celery/app/trace.py", line 629, in __protected_call__
    return self.run(*args, **kwargs)
  File "/opt/ori/ocd_backend/transformers/__init__.py", line 37, in run
    return self.transform_item(*args, item=item)
  File "/opt/ori/ocd_backend/transformers/__init__.py", line 78, in transform_item
    self.source_definition.get('doc_type', 'item'))
  File "/opt/ori/ocd_backend/items/goapi_meetingitem.py", line 17, in __init__
    data, item, processing_started)
  File "/opt/ori/ocd_backend/items/__init__.py", line 62, in __init__
    self._construct_object_meta(processing_started)
  File "/opt/ori/ocd_backend/items/__init__.py", line 75, in _construct_object_meta
    self.meta['original_object_id'] = self.get_original_object_id()
  File "/opt/ori/ocd_backend/items/goapi_meetingitem.py", line 54, in get_original_object_id
    return unicode(self.original_item['id']).strip()
```

**Comment by jurrian** [comment]
That doesn't seem related to the doc_type problem. Looks like the source data doesn't contain an id, can you show me the meetingitem source data the extractor returned?

**Comment by breyten** [comment]
```
{749: {u'documents': [{u'description': u'Uitnodiging bijeenkomst rekenkamercommissie om huidige kwaliteit programmabegroting te bespreken en verbeterpunten vast te stellen', u'confidential': False, u'modified': u'2017-11-09 10:09:12', u'filename': u'Uitnodiging.pdf', u'filesize': 167117, u'id': 11188}], u'description': u'', u'title': u'Uitnodiging', u'number': u'1.', u'sortorder': 1, 'date': u'2017-11-27 19:30:00', u'id': 4531}}
```

Can't really tell. output seems ok. But can you check this on your end (This was Goirle)?

**Comment by jurrian** [comment]
Finally found out what was going wrong: there was a call to original_item before it had properly been set. It should work now.
