### ISSUE TITLE
Lelystad (iBabs) does not work because they don't have commissies defined

### ISSUE THREAD

**Issue by breyten** [openstate/open-raadsinformatie#55]
Getting committtees in iBabs works by scanning lists for the word 'Commissie', but for example Lelystad does not have them.

![image](https://user-images.githubusercontent.com/154791/33666548-9d9b7b6a-da9a-11e7-93c5-92f73456c609.png)

This results in the following error:
```
[2017-12-06 15:27:10] [celery.app.trace] [ERROR] - Task ocd_backend.transformers.BaseTransformer[519e502e-d9ad-499e-99bc-7869eb217d62] raised unexpected: TypeError("'NoneType' object is not iterable",)
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/celery/app/trace.py", line 374, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/celery/app/trace.py", line 629, in __protected_call__
    return self.run(*args, **kwargs)
  File "/opt/ori/ocd_backend/transformers/__init__.py", line 37, in run
    return self.transform_item(*args, item=item)
  File "/opt/ori/ocd_backend/transformers/__init__.py", line 78, in transform_item
    self.source_definition.get('doc_type', 'item'))
  File "/opt/ori/ocd_backend/items/__init__.py", line 63, in __init__
    self._construct_combined_index_data()
  File "/opt/ori/ocd_backend/items/__init__.py", line 81, in _construct_combined_index_data
    for field, value in self.get_combined_index_data().iteritems():
  File "/opt/ori/ocd_backend/items/ibabs_meeting.py", line 67, in get_combined_index_data
    committees = self._get_committees()
  File "/opt/ori/ocd_backend/items/ibabs_meeting.py", line 42, in _get_committees
    return {self._find_meeting_type_id(c): c for c in results}
TypeError: 'NoneType' object is not iterable
```

**Comment by jurrian** [comment]
I've encountered this problem in another municipality as well. I guess we have to settle for a fallback to 'Raadsvergadering' or even Council if it's missing. Any better ideas?

**Comment by breyten** [comment]
Yeah, just try/catching the error would be best here
