### ISSUE TITLE
Notubiz meeting (items?) should be processed even when they do not have a description

### ISSUE THREAD

**Issue by breyten** [openstate/open-raadsinformatie#60]
```
[2018-01-23 14:40:41] [celery.app.trace] [ERROR] - Task ocd_backend.transformers.BaseTransformer[73d07efe-d538-45d2-9f55-0517a910314c] raised unexpected: KeyError('3',)
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/celery/app/trace.py", line 374, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/celery/app/trace.py", line 629, in __protected_call__
    return self.run(*args, **kwargs)
  File "/opt/ori/ocd_backend/transformers/__init__.py", line 37, in run
    return self.transform_item(*args, item=item)
  File "/opt/ori/ocd_backend/transformers/__init__.py", line 78, in transform_item
    self.source_definition.get('doc_type', 'item'))
  File "/opt/ori/ocd_backend/items/__init__.py", line 63, in __init__
    self._construct_combined_index_data()
  File "/opt/ori/ocd_backend/items/__init__.py", line 81, in _construct_combined_index_data
    for field, value in self.get_combined_index_data().iteritems():
  File "/opt/ori/ocd_backend/items/notubiz_meeting.py", line 58, in get_combined_index_data
    combined_index_data['description'] = self.original_item['attributes']['3']
KeyError: '3'
```

**Comment by jurrian** [comment]
We need to make a permanent fix for those dynamic attributes later, I know that there is a page where all dynamic attributes are defined per municipality:
https://api.notubiz.nl/organisations?format=json&version=1.10.8
