### ISSUE TITLE
ori_frontend: module Celery not found

### ISSUE THREAD

**Issue by bliekp** [openstate/open-raadsinformatie#89]
When starting with docker-compose in the production branch the ori_frontend container fails with the following logs:

`[2018-10-17 11:27:48 +0000] [1] [INFO] Starting gunicorn 19.8.1,
[2018-10-17 11:27:48 +0000] [1] [INFO] Listening at: http://0.0.0.0:5000 (1),
[2018-10-17 11:27:48 +0000] [1] [INFO] Using worker: sync,
[2018-10-17 11:27:48 +0000] [11] [INFO] Booting worker with pid: 11,
[2018-10-17 11:27:48 +0000] [12] [INFO] Booting worker with pid: 12,
[2018-10-17 11:27:48 +0000] [11] [ERROR] Exception in worker process,
Traceback (most recent call last):,
  File "/usr/local/lib/python2.7/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker,
    worker.init_process(),
  File "/usr/local/lib/python2.7/site-packages/gunicorn/workers/base.py", line 129, in init_process,
    self.load_wsgi(),
  File "/usr/local/lib/python2.7/site-packages/gunicorn/workers/base.py", line 138, in load_wsgi,
    self.wsgi = self.app.wsgi(),
  File "/usr/local/lib/python2.7/site-packages/gunicorn/app/base.py", line 67, in wsgi,
    self.callable = self.load(),
  File "/usr/local/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 52, in load,
    return self.load_wsgiapp(),
  File "/usr/local/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 41, in load_wsgiapp,
    return util.import_app(self.app_uri),
  File "/usr/local/lib/python2.7/site-packages/gunicorn/util.py", line 350, in import_app,
    __import__(module),
  File "/opt/ori/ocd_frontend/wsgi.py", line 7, in <module>,
    from ocd_frontend import rest,
  File "/opt/ori/ocd_frontend/rest/__init__.py", line 6, in <module>,
    from ocd_frontend.factory import create_app_factory,
  File "/opt/ori/ocd_frontend/factory.py", line 4, in <module>,
    from celery import Celery,
ImportError: No module named celery,
[2018-10-17 11:27:48 +0000] [11] [INFO] Worker exiting (pid: 11),
[2018-10-17 11:27:48 +0000] [12] [ERROR] Exception in worker process,
Traceback (most recent call last):,
  File "/usr/local/lib/python2.7/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker,
    worker.init_process(),
  File "/usr/local/lib/python2.7/site-packages/gunicorn/workers/base.py", line 129, in init_process,
    self.load_wsgi(),
  File "/usr/local/lib/python2.7/site-packages/gunicorn/workers/base.py", line 138, in load_wsgi,
    self.wsgi = self.app.wsgi(),
  File "/usr/local/lib/python2.7/site-packages/gunicorn/app/base.py", line 67, in wsgi,
    self.callable = self.load(),
  File "/usr/local/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 52, in load,
    return self.load_wsgiapp(),
  File "/usr/local/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 41, in load_wsgiapp,
    return util.import_app(self.app_uri),
  File "/usr/local/lib/python2.7/site-packages/gunicorn/util.py", line 350, in import_app,
    __import__(module),
  File "/opt/ori/ocd_frontend/wsgi.py", line 7, in <module>,
    from ocd_frontend import rest,
  File "/opt/ori/ocd_frontend/rest/__init__.py", line 6, in <module>,
    from ocd_frontend.factory import create_app_factory,
  File "/opt/ori/ocd_frontend/factory.py", line 4, in <module>,
    from celery import Celery,
ImportError: No module named celery,
[2018-10-17 11:27:48 +0000] [12] [INFO] Worker exiting (pid: 12),
[2018-10-17 11:27:48 +0000] [1] [INFO] Shutting down: Master,
[2018-10-17 11:27:48 +0000] [1] [INFO] Reason: Worker failed to boot.,`

**Comment by jurrian** [comment]
Have you tried rebuilding the frontend image?
